package com.example.ciclomenstrual.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "notes")
data class RoomNote(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val date: Long,
    // Nullable at the storage boundary to retain the exact schema generated by the legacy Java entity.
    val content: String?,
)
